### ISSUE TITLE
When updating scope no "some are selected" symbols appear

### ISSUE THREAD

**Issue by AshMcConnell** [iVantage/angular-ivh-treeview#146]
Hi Folks,

If I change one of the leaf nodes to be selected by setting the model (i.e. leaf.selected = true) I expected to see the "some are selected" symbols, but the checkboxes are all empty.  It works when I manually click the box

Am I missing some option?

![image](https://cloud.githubusercontent.com/assets/497941/17474832/ea70f3c6-5d4f-11e6-8b1a-5923138cef71.png)

Thanks for your help!
Ash

**Comment by jtrussell** [comment]
Instead of modifying selected properties directly (i.e. `leaf.selected = true`) use the [ivhTreeviewMgr](https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewmgrselecttree-node-opts-isselected) service to change selected states (i.e. `ivhTreeviewMgr.select(myTree, leaf)`). Otherwise, as you noted, selection changes won't propagate through the tree - this done intentionally to ensure data consistency.

**Comment by AshMcConnell** [comment]
Thanks, I didn't realise you could do it without referencing the dom, but it works when using the model data, perfect!
