### ISSUE TITLE
Filter only selected nodes

### ISSUE THREAD

**Issue by vlados** [iVantage/angular-ivh-treeview#154]
Hey,
I've managed to do everything that I wanted with the treeview but the only problem is that I cannot manage to pass custom filter function to the component so I can filter only the nodes that have selected: true
How I can do this?

**Comment by jtrussell** [comment]
This is a little tricky as sometimes a parent will not be selected but have selected children. In this case you probably want don't want to filter out the parent.

You might be able to use `ivhTreeviewOptions`, grab the selected and indeterminate attributes, then use these together with your usual filter. Here's a rough example, not that the filter only applies to things which are selected.

http://jsbin.com/kutiboyuxa/1/edit?html,js,output

**Comment by vlados** [comment]
Yes, but for some reason on filtering is selecting the parent nodes if all child nodes are selected. I made a workaround for this behaviour by using checkboxes, but I don't understand why is doing this on filtering.
Simple code:
```

		ivhTreeviewOptionsProvider.set({
			twistieCollapsedTpl: '<span class="fa fa-plus-square-o"></span>',
			defaultSelectedState: false,
			twistieExpandedTpl: '<span class=" fa fa-minus-square-o"></span>',
			nodeTpl: [
				'<div class="ivh-treeview-node-content" title="{{trvw.label(node)}}">',
				'<span ivh-treeview-toggle>',
				'<span class="ivh-treeview-twistie-wrapper" ivh-treeview-twistie></span>',
				'</span>',
				'<label class="ivh-treeview-node-label" ng-class="{\'checked\':node.selected}">',
				'<span class="checkbox checkbox-default pull-left" onclick="($(\'input\',this).click())">',
				'	<input type="checkbox" ng-model="node.selected" ng-click=" trvw.onCbChange(node, node.selected);">',
				'	<label></label>',
				'</span>',
				'<span class="text">{{trvw.label(node)}}</span>',
				'</label>',
				'<div ivh-treeview-children></div>',
				'</div>'
			].join('\n'),
			twistieLeafTpl: ''
		});
```

**Comment by jtrussell** [comment]
IVH Treeview *will* select parent nodes as soon as all child nodes become selected. This is simply the selection model we've adopted - we define a parent to be selected if (and only if) all child nodes are selected. If you want different behavior you will need to use a custom template and insert your own checkboxes and selection management as you did above.

**Comment by vlados** [comment]
Yes, I've done that but why it's doing this behaviour on filter and how I can change it?

**Comment by jtrussell** [comment]
Sorry for not circling back sooner. It behaves this way because filtering is considered a *visibility* change only, as opposed to actually removing items from you tree. With the way our selection model works it would be very strange to have selections be affected by what's currently visible. Imagine you have a situation like the following:

- [ ] Parent
  - [x] Child 1
  - [x] Child 2
  - [ ] Child 3

Parent 1 is not considered selected (it would be indeterminate). Then suppose Child 3 is filtered, all of the Parent node's children would be selected. To maintain a consistent model representation we would have to *select* Parent whenever Child 3 gets filtered away.

Taken another way suppose you filter away some nodes than select a parent (select all *visible* children). If you then remove the filter the selected parent would now have unselected children, this is not allowed by selection model.
