### ISSUE TITLE
Bug when select a child

### ISSUE THREAD

**Issue by thomaspons** [iVantage/angular-ivh-treeview#173]
I have a strange behaviour. 

When i select a child using the default checkbox, it's select his parents. 

I've got a really simple array with children property and name property as label. 

The onlny specific thing is that i'm in a ui-modal view. 

Any ideas ? 

Thanks for your help

**Comment by jkrot** [comment]
So when you select your child it will do a partial select of the parent.  If you parent only has one tree level of the child it will be a full select.  Can you give an example of the tree?

**Comment by thomaspons** [comment]
Here is my tree : 

```
[{
    code: '1A',
    name: 'Name of 1A',
    children: [{
        code: '1B',
        name: 'Name of 1B',
        children: [{
            code: '1C',
            name: 'Name of 1C',
            children: []
        }]
    }]
}]
```

**Comment by jtrussell** [comment]
The behavior you're seeing is by design. The baked in selection model treats a node's selected state as invariant - a given node is selected if either all its children are selected or its parent is. If you'd like different behavior you just need to swap out the provided checkbox directive for one of your own making in your node template. `ivhTreeviewBfs` will be helpful in walking through a given node's children recursively to mark them as selected.
