### ISSUE TITLE
Binding children on promise resolve does not update UI

### ISSUE THREAD

**Issue by r4hulp** [iVantage/angular-ivh-treeview#205]
Hi,

We want to bind the response that we get from WebAPI to treeview. On promise resolve, we update tree children with the ones we got in response. However the UI does not update unless and until we click on parent node explicitly on UI..

How can we achieve this?

Sample - http://jsbin.com/cutesug/1/edit?html,js,output

Sample imitates the problem we are facing. When I set new tree on setTimeout, it does not update the UI..

Is there any better way to do it?

**Comment by jtrussell** [comment]
This is an issue with stepping outside angular and not letting angular know you've made changes it should know about. You can use `$timeout` instead of `setTimeout` or fire off `$scope.$apply()` after you've made your changes. I updated your example to demonstrate (FYI I found it a little confusing to reference the controller intance as `$scope`, the name of something you may want to inject):

```
app.controller('DemoCtrl', DemoCtrl);

DemoCtrl.$inject = ['ivhTreeviewMgr', '$scope'];
function DemoCtrl(ivhTreeviewMgr, scope) {
  this.stuff = stuff;
  var $scope = this;
  
  setTimeout(function(){
    $scope.stuff = stuff2;
    ivhTreeviewMgr.deselectAll($scope.stuff);
    // setTimeout steps us out of Angular's dirty checking.
    // Tell angular you've made changes it should know about
    scope.$apply();
  },2000);
  
}
```

**Comment by r4hulp** [comment]
Hi @jtrussell,

thanks for the reply. In my example, I wouldn't be using either `setTimeout` or `$timeout` but update the database after promise resolution. Also, I am utilizing it in AngularJS components where scope is non existent. How would I let angular know that I've made changes in such scenario?
