### ISSUE TITLE
Problem faced when using selected in parent node

### ISSUE THREAD

**Issue by Saideprinz** [iVantage/angular-ivh-treeview#38]
I included this ivh treeview in my angularjs project to display tree structure. I followed this link
http://jsbin.com/guzopedimi/1/edit?html,js,output
Now when its gets loaded i use same data specified in link. For me only the parent node(ie Pen is checked) is getting selected and child nodes are not selected(values under Pen node is not checked while loading) even if parents value should be inherit. 
When i am unchecking and checking the parent Node then all the child nodes are also getting checked. 
Can you help me with this issue.

**Comment by jtrussell** [comment]
You want the validate on startup option:

https://github.com/ivantage/angular-ivh-treeview#validate-on-startup

The behavior you're describing is by design. By default we won't change your selections except by user interaction. That option allows you to tell the treeview to validate its node selected states on startup.

You may also want to read the section on node default selected states:

https://github.com/iVantage/angular-ivh-treeview#default-selected-state
