### ISSUE TITLE
Add options to disable toggle on label click and to disable node click on toggle

### ISSUE THREAD

**Issue by klemens-kunz** [iVantage/angular-ivh-treeview#51]
I needed some additional functionality for the treeview:
1. Disable expand/collapse toggling, if a user clicks on a node label
2. Disable triggering a node click, if a user clicks on a node twistie

I ended up adding an option for (1) and updating the toggle directive accordingly. For (2) I separated the click handler from the toggle directive by creating a click directive and updating the default node template in the options.

If this is functionality you'd be interested in and you're not working on something similar at the moment, I'd like to open a PR with these changes.

**Comment by jtrussell** [comment]
Interesting. We were planning to rename the click handler to "toggle-callback" or some such (#45). So  I think it might make sense to leave the callback invocation code there rather than split it out. I could get behind adding a way to stop clicks on labels from toggling the node though. It probably ought to be something similar to how checkboxes are enabled/disabled so that folks who make their own custom templates can honor that setting if need be. Exposed by the `ivhTreeview` controller and handled in the node template. Seem reasonable?

**Comment by jtrussell** [comment]
In the `v1` (hopefully soon to be merged in) "click" is renamed to toggle as mentioned above.

Since the label click behavior is fairly specific that may be better left for custom templates to sort out. Open to other opinions though.

**Comment by AbhishekGarg** [comment]
Hi @jtrussell ,
Custom templates is a great option. Though, I believe it results in lot of "template redundancy" in case it has to be applied in multiple places, nodeTpl definitely helps here.

Since ivhtreeview is so much configurable, a handler for label click would be great. I found it easy to implement, basis the older click handler (renamed to toggle).

I would be willing to submit a PR if you are still interested in this.
