### ISSUE TITLE
Controller Scope in Click Callback is wrong

### ISSUE THREAD

**Issue by digitalkaoz** [iVantage/angular-ivh-treeview#53]
the tree renders nicely, filtering collapsing works, the `click-handler` is triggered, but its in the wrong scope (`Window`) i expect it to be in the ControllerScope.
setting the clickHandler from the `Controller.treeOptions` wont worked as described in the docs.

i need the correct scope to do other things in the controller.

here me faulty code: 

```ts
class Controller {

    query;   

    tree = {
       caption : "foo",
       children: [
           {caption:"bar"}, {caption:"baz"}
       ]
    };

    treeOptions = {
        useCheckboxes: false,
        labelAttribute: 'caption'
    };

    select(node) {
        console.log(this, node); //scope is window here
    }
}

export default () => {
    return {
        restrict: 'E',
        bindToController: {
            type: '@',
            label: '@'
        },
        scope: true,
        controllerAs: 'category',
        controller: Controller,
        templateUrl: 'components/product/values/category.html'
    };
};
```

```html
<div 
    ivh-treeview="category.tree"
    ivh-treeview-options="category.treeOptions"
    ivh-treeview-click-handler="category.select"
>
</div>
```

**Comment by jtrussell** [comment]
Unless I'm mistaken that's just how scoping works in JS:

```javascript
function Foo() {
  this.whatIsThis = function() {
    console.log(this);
  };
}

var f = new Foo();

f.whatIsThis();
// -> Foo {}

var hmmm = f.whatIsThis;
hmmm();
// -> Window {...}
```

When you pass a reference to `select` to the directive it is no longer attached to a `Controller` instance. If you'd like it to retain that context you'll need to bind it yourself or do something of the sort.

**Comment by digitalkaoz** [comment]
@jtrussell sure thats scoping in JS.

but thats not the desired behavior.

i could think of a additional option like `ivh-treeview-callback-scope="category"` which binds the callbacks to this scope.

or as you said use the `ng-click` approach.

we cant bind ourself to a specific scope, because angular doesnt allows it:
`Error: [$parse:isecff] Referencing call, apply or bind in Angular expressions is disallowed! Expression: category.select.bind(category)`

if i try it like this:

`ivh-treeview-click-handler="category.select.bind(category)"`

**Comment by jtrussell** [comment]
Angular may not let you bind directly in an expression but there's no reason you can't bind your function elsewhere. Or make a local reference to `this` if you need it to be preserved regardless of how your function is called:

```javascript
function Foo() {
  var self = this;

  this.whatIsThis = function() {
    console.log(this);
  };

  this.whatWasThis = function() {
    console.log(self);
  };

  this.whatWasThis2 = function() {
    console.log(this);
  }.bind(this);
}

var f = new Foo();
  , a = f.whatIsThis
  , b = f.whatWasThis
  , c = f.whatWasThis2

a(); // --> Window {...}
b(); // --> Foo {}
c(); // --> Foo {}
```

The reason we went with callbacks rather than `$eval`ed expressions (a la `ngClick`) was so we could pass references to the node being clicked and the owning tree to the callback. I added an item to our v1 roadmap (#27) to investigate making a switch to having these be expression based. I don't expect we'll introduce any breaking changes until the v1 release though so until then you'll be stuck working with callback references and all that implies. Feel free to comment here (#55) as well.
