### ISSUE TITLE
Question: ng-click in custom template doesnt fire

### ISSUE THREAD

**Issue by digitalkaoz** [iVantage/angular-ivh-treeview#54]
thats my template:

```html
<div ng-init="category.load()"
              ivh-treeview="category.choices.entity.children" 
              ivh-treeview-filter="category.query"
              ivh-treeview-options="category.treeOptions"
          >
              <script type="text/ng-template" id="nodes-template.html">
                  <div class="tree-node">
                    <span ivh-treeview-toggle>
                      <span ivh-treeview-twistie></span>
                    </span>
                   <span class="ivh-treeview-node-label">
                     {{trvw.label(node)}}
                   </span>
                   <a class="btn btn-xs btn-primary pull-right" ng-click="alert('foo')"><i class="glyphicon glyphicon-star"></i></a>
                   <div ivh-treeview-children class="clearfix"></div>
                 </div>
              </script>          
</div>
```

the `ng-click` inside the `a` doesnt fire, so no `alert`! what might be wrong here?

**Comment by michal-husak** [comment]
@digitalkaoz have you solved that?

**Comment by digitalkaoz** [comment]
yeah by using another tree component ;)

**Comment by michal-husak** [comment]
:D can you tell me which?

**Comment by digitalkaoz** [comment]
in the end it was some jquery treeview component, not as sexy as a angular one, but that one worked ;)

**Comment by jtrussell** [comment]
Just FYI there's no reason you can't use ng-click inside a template. Your example doesn't work simply because `alert` is not defined within the context of your angular expression. E.g.:

```
<body ng-app="myApp">
  <button ng-click="alert('foo')">clicky</button>
</body>
```

Clicking the button here will not generate an alert.

**Comment by michal-husak** [comment]
I don't know what I'm doing wrong, but I've tried several places where to put ng-click.
```html
<div ivh-treeview="stuff"
        ivh-treeview-use-checkboxes="false"
        ivh-treeview-on-toggle="treeNodeClick(ivhNode)"
        ivh-treeview-id-attribute="'driveId'"
>
    <script type="text/ng-template">
        <div title="{{trvw.label(node)}}" ng-click="clickHandler()">
            <span ivh-treeview-toggle>
                <span ivh-treeview-twistie></span>
            </span>
            <span class="ivh-treeview-node-label" ivh-treeview-toggle ng-class="{active: node.active}" ng-click="clickHandler()">
                <i class="fa fa-folder" ng-if="!trvw.isExpanded(node)"></i>
                <i class="fa fa-folder-open" ng-if="trvw.isExpanded(node)"></i>
                {{trvw.label(node)}}<a ng-click="clickHandler()">click me</a>
            </span>
            <div ivh-treeview-children></div>
        </div>
    </script>
</div>
```
In the controller I have ``treeNodeClick(ivhNode)`` which is set in ``ivh-treeview-on-toggle``. It works fine. But in the same controller I have also ``clickHandler()``:
```javascript
$scope.clickHandler = function() {
    console.log('clicked!');
};
```
and it doesn't work.

I need that functionality because I want to be able to handle ``ivh-treeview-on-toggle`` on a node which has empty or none ``children`` property.

@jtrussell do you have any workaround for this?

**Comment by jtrussell** [comment]
Each node has an isolate scope - even when passing the template as transcluded content you won't have access to the transcluded scope. The means individual nodes can't see methods exposed by your controller.

You can use events (e.g. `ng-click="$emit('trvw_click', node)"`), create a directive which attaches click handlers to your nodes, etc.

BTW - Are you hoping to fetch new nodes when a "leaf" is expanded? You may want to consider creating a directive which does that and using it as the leaf twistie.

**Comment by michal-husak** [comment]
I have a following component:
<img width="897" alt="snimka obrazovky 2015-11-11 o 15 59 59" src="https://cloud.githubusercontent.com/assets/5699580/11094286/2f6b14d4-888f-11e5-9efc-2dc6c2239451.png">
On the left is the tree which code I mentioned in the comment above.
On the right is simple ng-repeat list of the content of folder selected in the tree on the left.
You can see blue expanded folder *Marketing* on the left and it's content fetched from the Google Drive API. 
What I want is, when I click on the folder *HR* (which has no children in the tree model because only folders are loaded in the tree) then content of this folder will fetch to the right side.
I can't do that because when the node is a leaf, none of the listeners can handle it.

**Comment by jtrussell** [comment]
Yes, I'd suggest using a leaf node template that supports "async" expanding and also communicates fetched nodes as necessary (e.g. by broadcasting an event or interacting with a service). Here's a rough hacked together demo:

http://jsbin.com/vatexa/edit?js,console,output

**Comment by michal-husak** [comment]
Thx, finally I solved it by ``ng-click="$emit('trvw_click', node)"``.
Maybe you can do something like ``ivh-treeview-on-click`` handler similar to ``ivh-treeview-on-toggle`` to cover these cases.
