### ISSUE TITLE
Custom label if...

### ISSUE THREAD

**Issue by meydey232** [iVantage/angular-ivh-treeview#60]
Hi again,
I need new future in my tree. So I have an array with my labels and childrens but currently I added one more element: flag. I need to highlight on green background of labels which is available. For example I have element: Hat which is available so I want to have green background - in my array it looks like:
[{label: 'Hats',
  flag: 'available',
  children: [
    {label: 'Flat cap'},
    {label: 'Fedora'},
]}]
Will be three states: available (green), few available (yellow), not available (red). If not available checkbox must be disabled. I've got directive to highlight selected items but how to do this? 

One more thing - if you could add some examples on jsbin how to use templates would be great.

**Comment by jtrussell** [comment]
Maybe something like this could get you going?

http://jsbin.com/zanawo/1/edit?html,css,js,output

**Comment by meydey232** [comment]
That's it! :)
Any ideas how to switch off checkbox there where I've got "qty < 0" ?

**Comment by jtrussell** [comment]
You'll probably end up wanting to make your own checkbox directive to substitute in the template. Just using `ng-hide` or some such with the `ivh-treeview-checkbox`es won't work so well (as you probably discovered) since parent nodes will still consider the selected state of all children when setting their own checkbox state... even those where qty === 0.

**Comment by jtrussell** [comment]
Closing but feel free to reopen if needed.
