### ISSUE TITLE
get value of a node's parent?

### ISSUE THREAD

**Issue by eiclkun** [iVantage/angular-ivh-treeview#71]
Can you add a little more detail in documentation for `ivh-treeview-change-handler`?
Took me quite a while to realize it's a predefined function with three predefined parameters.

~~Is there anyway to get a reference of current node's parent? Also could you provide an example of `trvw`? All I get was a Boolean value~~
~~```referenceList.filterCtrl = function(node, trvw){
        console.log(trvw);
}```~~

~~Output: `trvw = true` if it's a parent node.~~

**Comment by jtrussell** [comment]
At this point I'd suggest working with the v1.0.0 release candidate and using `ivh-treeview-on-cb-change`. You get to use a proper expression rather than just a predefined function. The docs are a bit better too, hopefully.

https://github.com/iVantage/angular-ivh-treeview/tree/v1#selectdeselect-handlers
