### ISSUE TITLE
Using (some) directives in node template generates error

### ISSUE THREAD

**Issue by BDomzalski** [iVantage/angular-ivh-treeview#74]
Hi,
I encountered a problem when using custom template for node. I needed a checkbox to be rendered a bit differently (so I can custom style it) so I took definition of ivhTreeviewCheckbox and create a new one based on its code which then I used in node template. I added a linking function to my directive and that made it throw an exception: "Error: [$compile:ctreq] Controller 'ivhTreeviewNode', required by directive 'myCheckbox', can't be found![...]". It looks like it have something to do with compilation by ivhTreeviewCompiler. To reproduce this issue you can add an empty link function to ivhTreeviewCheckbox.
I ended up just not requiring that controller but do you know what is causing the issue?

By the way I also spotted two things in the source code (checked for some cases):
- in ivhTreeviewNode directive there seems to be no need to define template (looks like control is working without it),
- in ivhTreeviewCompiler element.contents().remove(); looks also like it is not needed.

**Comment by jtrussell** [comment]
It's not "done" yet but you can see a nice custom checkbox example on our github pages - http://ivantage.github.io/angular-ivh-treeview/#demo-custom-templates.

You get an error when adding a link function to `ivhTreeviewCheckbox` because the `ivhTreeviewNode` directive does not have a controller. Angular looks for the required directive's controller and passes it as a fourth argument to the requiring directive's linking function, and in this case the controller does not exist. I can see how that would be confusing so I just swapped out the require statement to look for `ivhTreeview` instead, it accomplishes essentially the same thing but won't lead folks to the issue you're seeing here.

As for the other things:

- You are correct we don't actually need a template in `ivhTreeviewNode` I have removed it - thanks!
- `ivhTreeviewCompiler element.contents().remove()` **is** necessary as long as `ivhTreeviewNode` has a recursive template. But now that we removed (per the last item) it we can get rid of this line too. Nice.

**Comment by BDomzalski** [comment]
Didn't thought about that required directive simply has no controller. I assumed that if it is used somewhere else it is in place and works.
Thanks for clarification. Demo page looks nice!
